# Fichero `adult.csv` — Preparación de datos y modelo supervisado

Este notebook reúne **todo lo trabajado** hasta ahora:
1. Carga del dataset `adult.csv`
2. Creación del **dataset reducido** (solo columnas objetivo)
3. Limpieza de valores ausentes (`?` → `NaN`) y eliminación de filas incompletas
4. Definición de **X** e **y** (objetivo: `income`)
5. Identificación de variables **numéricas** y **categóricas**
6. Preprocesado con **ColumnTransformer** (StandardScaler + OneHotEncoder)
7. División **train/test**
8. Entrenamiento de un **modelo** (Regresión Logística)
9. Evaluación básica (classification report + matriz de confusión)

## 1. Carga del dataset

Nos aseguramos de que `adult.csv` está en la misma carpeta que este notebook.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df_adults = pd.read_csv('adult.csv')

df_adults.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

## 2. Creación del dataset reducido (solo columnas objetivo)
**Variables que se conservarán (las únicas permitidas en la práctica):**

In [4]:
#df_adults.drop(columns=['fnlwgt', 'education-num','marital.status', 'relationship','native.country'], inplace=True)

wished_columns = [
    'age', 'workclass', 'education', 'occupation', 'hours.per.week', 'income', 
    'race', 'sex','capital.gain', 'native.country', 'capital.loss'
]

df_model = df_adults[wished_columns].copy()

print(df_model.info())
print(df_model.shape)
df_model.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   education       32561 non-null  object
 3   occupation      32561 non-null  object
 4   hours.per.week  32561 non-null  int64
 5   income          32561 non-null  object
 6   race            32561 non-null  object
 7   sex             32561 non-null  object
 8   capital.gain    32561 non-null  int64
 9   native.country  32561 non-null  object
 10  capital.loss    32561 non-null  int64
dtypes: int64(4), object(7)
memory usage: 2.7+ MB
None
(32561, 11)

,age,workclass,education,occupation,hours.per.week,income,race,sex,capital.gain,native.country,capital.loss
0,90,?,HS-grad,?,40,<=50K,White,Female,0,United-States,4356
1,82,Private,HS-grad,Exec-managerial,18,<=50K,White,Female,0,United-States,4356
2,66,?,Some-college,?,40,<=50K,Black,Female,0,United-States,4356
3,54,Private,7th-8th,Machine-op-inspct,40,<=50K,White,Female,0,United-States,3900
4,41,Private,Some-college,Prof-specialty,40,<=50K,White,Female,0,United-States,3900

## 3. Limpieza del dataset reducido

En adult.csv, los valores ausentes a veces aparecen como `?` en algunas columnas, como podemos ver en la celda anterior
- Sustituimos `?` por `NaN`
- Comprobamos nulos por columna

In [6]:
df_model.replace('?', np.nan, inplace=True)
df_model.head()

,age,workclass,education,occupation,hours.per.week,income,race,sex,capital.gain,native.country,capital.loss
0,90,NaN,HS-grad,NaN,40,<=50K,White,Female,0,United-States,4356
1,82,Private,HS-grad,Exec-managerial,18,<=50K,White,Female,0,United-States,4356
2,66,NaN,Some-college,NaN,40,<=50K,Black,Female,0,United-States,4356
3,54,Private,7th-8th,Machine-op-inspct,40,<=50K,White,Female,0,United-States,3900
4,41,Private,Some-college,Prof-specialty,40,<=50K,White,Female,0,United-States,3900

## 4. Definir el problema supervisado: predicción de salario (`income`)

In [ ]:
"""
Predecir si una persona gana mas de 50K al año en función de sus demás características.

Caso binario, solo hay 2 posibles valores: <=50K y >50K
"""

## 5. Identificación de variables numéricas y categóricas

De lo anterior vemos que hay:
- variables numéricas: 
- variables categóricas:

In [ ]:
"""
numericas: age, hours.per.week, capital.gain, capital.loss
categoricas: workclass, education, occupation, race, sex, native.country, income
"""

### Preprocesado de los datos

En esta fase se preparan las variables para su uso en el modelo de Machine Learning.
Dado que el conjunto de datos contiene variables numéricas y categóricas, se aplican
técnicas de preprocesado diferenciadas, incluyendo la imputación de valores nulos,
el escalado de variables numéricas y la codificación de variables categóricas mediante
One-Hot Encoding.

## 6. Preprocesado con sklearn

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

x = df_model[['age','hours.per.week','capital.gain','capital.loss']]
y = df_model['income']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state = 42
)

Ahora terminamos de preparar todo

## 7. División en entrenamiento y prueba

### Entrenamiento del modelo

Una vez definidos el conjunto de entrenamiento y el preprocesado de los datos,
se procede al entrenamiento de un modelo de clasificación basado en regresión logística,
utilizado como modelo base para este problema.

In [9]:
model = LinearRegression()
model.fit(x_train, y_train)

ValueError: could not convert string to float: '<=50K'

## 8. Regresión

### Evaluación del modelo

El rendimiento del modelo se evalúa utilizando distintas métricas de clasificación,
así como la matriz de confusión, con el objetivo de analizar su capacidad predictiva
y detectar posibles limitaciones.

## 9. Evaluación del modelo